package com.configserver.officerspro.complainandfirservice.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * DTO for {@link com.configserver.officerspro.complainandfirservice.entity.Document}
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FIRDocumentDTO {
    private Long documentId;
    private String fileName;
    private String originalFileName;
    private String fileType;
    private String filePath;
    private Long fileSize;
    private String documentType;
    private String description;
    private Boolean isActive;
    private Integer createdBy;
    private LocalDateTime createdOn;
    private Integer updatedBy;
    private LocalDateTime updatedOn;
    private Long firId;
    
    public static FIRDocumentDTOBuilder builder() {
        return new FIRDocumentDTOBuilder();
    }
    
    public static class FIRDocumentDTOBuilder {
        private Long documentId;
        private String fileName;
        private String originalFileName;
        private String fileType;
        private String filePath;
        private Long fileSize;
        private String documentType;
        private String description;
        private Boolean isActive = true;
        private Integer createdBy;
        private LocalDateTime createdOn;
        private Integer updatedBy;
        private LocalDateTime updatedOn;
        private Long firId;
        
        public FIRDocumentDTOBuilder documentId(Long documentId) {
            this.documentId = documentId;
            return this;
        }
        
        public FIRDocumentDTOBuilder fileName(String fileName) {
            this.fileName = fileName;
            return this;
        }
        
        public FIRDocumentDTOBuilder originalFileName(String originalFileName) {
            this.originalFileName = originalFileName;
            return this;
        }
        
        public FIRDocumentDTOBuilder fileType(String fileType) {
            this.fileType = fileType;
            return this;
        }
        
        public FIRDocumentDTOBuilder filePath(String filePath) {
            this.filePath = filePath;
            return this;
        }
        
        public FIRDocumentDTOBuilder fileSize(Long fileSize) {
            this.fileSize = fileSize;
            return this;
        }
        
        public FIRDocumentDTOBuilder documentType(String documentType) {
            this.documentType = documentType;
            return this;
        }
        
        public FIRDocumentDTOBuilder description(String description) {
            this.description = description;
            return this;
        }
        
        public FIRDocumentDTOBuilder isActive(Boolean isActive) {
            this.isActive = isActive;
            return this;
        }
        
        public FIRDocumentDTOBuilder createdBy(Integer createdBy) {
            this.createdBy = createdBy;
            return this;
        }
        
        public FIRDocumentDTOBuilder createdOn(LocalDateTime createdOn) {
            this.createdOn = createdOn;
            return this;
        }
        
        public FIRDocumentDTOBuilder updatedBy(Integer updatedBy) {
            this.updatedBy = updatedBy;
            return this;
        }
        
        public FIRDocumentDTOBuilder updatedOn(LocalDateTime updatedOn) {
            this.updatedOn = updatedOn;
            return this;
        }
        
        public FIRDocumentDTOBuilder firId(Long firId) {
            this.firId = firId;
            return this;
        }
        
        public FIRDocumentDTO build() {
            FIRDocumentDTO dto = new FIRDocumentDTO();
            dto.setDocumentId(this.documentId);
            dto.setFileName(this.fileName);
            dto.setOriginalFileName(this.originalFileName);
            dto.setFileType(this.fileType);
            dto.setFilePath(this.filePath);
            dto.setFileSize(this.fileSize);
            dto.setDocumentType(this.documentType);
            dto.setDescription(this.description);
            dto.setIsActive(this.isActive);
            dto.setCreatedBy(this.createdBy);
            dto.setCreatedOn(this.createdOn);
            dto.setUpdatedBy(this.updatedBy);
            dto.setUpdatedOn(this.updatedOn);
            dto.setFirId(this.firId);
            return dto;
        }
    }
    
    // Getters and Setters (generated by @Data)
}
